<a href="https://colab.research.google.com/github/Kamali1265/ML-Ops-Tasks/blob/main/Day-3/linear_regression_multivariate_traffic_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Multiple Linear Regression**

**Problem Statement**

Predict traffic density based on multiple traffic-related factors such as vehicle count, average speed, and horn count using Multiple Linear Regression.

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [4]:
df = pd.read_csv("traffic_multiple_lr.csv")

df.head()

   Vehicle_Count  Avg_Speed  Horn_Count  Traffic_Density
0             87         46          32            66.05
1             76         64          52            59.80
2             47         30          57            59.90
3             96         51          27            67.10
4            194         41           5           109.20

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Vehicle_Count    50 non-null     int64
 1   Avg_Speed        50 non-null     int64
 2   Horn_Count       50 non-null     int64
 3   Traffic_Density  50 non-null     float64
dtypes: float64(1), int64(3)
memory usage: 1.7 KB

In [6]:
df.isnull().sum()

Vehicle_Count      0
Avg_Speed          0
Horn_Count         0
Traffic_Density    0
dtype: int64

In [7]:
reg = linear_model.LinearRegression()

In [8]:
reg.fit(df[['Vehicle_Count',
            'Avg_Speed',
            'Horn_Count']],

        df['Traffic_Density'])

LinearRegression()

In [9]:
reg.predict([[120, 40, 35]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([83.75])

In [10]:
reg.coef_

array([ 0.45, -0.35,  0.25])

In [11]:
reg.intercept_

np.float64(34.99999999999995)

In [12]:
reg.coef_[0]*120 + \
reg.coef_[1]*40 + \
reg.coef_[2]*35 + \
reg.intercept_

np.float64(83.75)

In [14]:
reg.predict([[180, 30, 50]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([118.])